version: "3.9"

services:
  app:
    build: .
    container_name: mytachodata_app
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpassword
    networks:
      - mynet

  db:
    image: mysql:8.0
    container_name: mytachodata_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet:
